version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: aircnc_api
    depends_on:
      - mongo
    networks:
      - aircnc_network
    ports:
      - 3333:3333
    restart: unless-stopped
    volumes:
      - ./api/:/app/
      - /app/node_modules/

  web:
    build:
      context: ./web
      target: deps
    command: yarn dev
    container_name: aircnc_web
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3333
    ports:
      - 3000:3000
    volumes:
      - ./web/:/app/
      - /app/.next
      - /app/node_modules/

  mongo:
    container_name: aircnc_mongo
    image: mongo
    networks:
      - aircnc_network
    ports:
      - 27017:27017
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

networks:
  aircnc_network:

volumes:
  mongo_data:
