services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: yarn dev
    container_name: aircnc_api
    depends_on:
      - mongo
    environment:
      API_URL: http://localhost:3333
      MONGODB_URI: mongodb://mongo:27017/aircnc
    networks:
      - aircnc_network
    ports:
      - 3333:3333
    volumes:
      - ./api/:/app/
      - /app/node_modules/

  frontend:
    build:
      context: ./frontend
      target: deps
    command: yarn dev
    container_name: aircnc_frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3333
    ports:
      - 3000:3000
    volumes:
      - ./frontend/:/app/
      - /app/.next
      - /app/node_modules/

  mongo:
    container_name: aircnc_mongo
    image: mongo
    networks:
      - aircnc_network
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

networks:
  aircnc_network:

volumes:
  mongo_data:
